Nicky/wd 61 rest library
trinitywayfinders/WayFinder pull request #16
Opened 2019-02-14 17:53 UTC by bonellon

Added Non-runnable REST Library.

ToDo: Do we need to write tests? How??

2019-02-18 12:17 UTC, ats0stv requested changes
Looks all good.
Just could you please remove the temp file like .project, /bin etc

2019-02-18 12:49 UTC, bonellon commented
PR Updated - removed temp files

2019-02-18 13:33 UTC, ats0stv submitted a review, later dismissed

2019-02-18 13:47 UTC, GeeseHoward commented on Code/Libraries/RESTLibrary/src/main/java/ie/tcd/wayfinders/restLibrary/Test.java
> +package ie.tcd.wayfinders.restLibrary;
Remove temp class

2019-02-18 13:49 UTC, GeeseHoward commented on Code/Libraries/RESTLibrary/src/test/java/ie/tcd/wayfinders/restLibrary/LibraryTest.java
> +    public void get_200OK_noProperties() throws IOException
Conform to camel case

2019-02-18 19:56 UTC, bonellon commented
@GeeseHoward  fixed comments, please confirm

2019-02-19 16:39 UTC, GrennanM submitted a review, later dismissed

2019-02-19 20:21 UTC, zihan0 approved these changes

2019-02-21 11:49 UTC, Jamesxu182 approved these changes

2019-02-21 12:07 UTC, merged