create an authentication server
trinitywayfinders/WayFinder pull request #18
Opened 2019-02-18 13:46 UTC by Jamesxu182

2019-02-19 16:50 UTC, bonellon submitted a review, later dismissed

2019-02-21 14:20 UTC, ats0stv requested changes

2019-02-21 14:20 UTC, ats0stv commented on auth/src/main/java/com/wayfinder/auth/config/AuthorisationServerConfig.java
> +		        .redirectUris("http://www.google.com");
Please change the redirect URI from google.com to something like localhost or so

2019-02-21 14:20 UTC, ats0stv commented on auth/src/main/java/com/wayfinder/auth/config/SwaggerConfig.java
> +        return new Docket(DocumentationType.SWAGGER_2)
Please add our app specific information
```java
@Configuration
@EnableSwagger2
public class SwaggerConfig {

    @Bean
    public Docket api()
    {
        return new Docket(DocumentationType.SWAGGER_2).apiInfo(wayfinderInfo())
                                                      .select()
                                                      .apis(RequestHandlerSelectors.any())
                                                      .paths(PathSelectors.any())
                                                      .build();
    }

    private ApiInfo wayfinderInfo()
    {
        Contact contact2 = new Contact("Wayfinders", "", "thundyia@tcd.ie");
        return new ApiInfoBuilder().title("Trinity Wayfinders Authentication Module")
                                   .description("Authentication ReST API Documentation")
                                   .contact(contact2)
                                   .version("0.1").build();
    }
}
```

2019-02-21 14:20 UTC, ats0stv commented on auth/bin/main/.gitignore
> +/com/
This file should be ignored. All of /bin/* should not be commited

2019-02-21 14:20 UTC, ats0stv commented on auth/bin/main/application.properties
> +spring.datasource.url = jdbc:mysql://localhost:3306/wayfinder?useSSL=false
This file should be ignored. All of /bin/* should not be committed

2019-02-21 16:05 UTC, ats0stv approved these changes

2019-02-21 16:06 UTC, bonellon commented on Code/AuthenticationServer/src/main/java/com/wayfinder/auth/config/AuthorisationServerConfig.java
> +
WHY ARE THERE 3 NEWLINES?

2019-02-21 16:06 UTC, bonellon commented on Code/AuthenticationServer/src/main/java/com/wayfinder/auth/config/SwaggerConfig.java
> +@EnableSwagger2
I THOUGHT WERE USING OPENAPI 3.0???????

2019-02-21 16:08 UTC, bonellon approved these changes

2019-02-21 16:08 UTC, bonellon commented on Code/AuthenticationServer/src/main/java/com/wayfinder/auth/entity/Authority.java
> +	 */
NICE COMMENT

2019-02-21 16:08 UTC, bonellon commented on Code/AuthenticationServer/src/main/java/com/wayfinder/auth/controller/UserController.java
> +    	OAuth2Authentication oauth2Authentication = (OAuth2Authentication) SecurityContextHolder.getContext().getAuthentication();
TEST

2019-02-21 16:08 UTC, merged