secure high level APIs
trinitywayfinders/WayFinder pull request #22
Opened 2019-02-21 17:49 UTC by Jamesxu182

2019-02-22 13:57 UTC, ats0stv requested changes

2019-02-22 13:57 UTC, ats0stv commented on Code/HighLevelAPI/src/main/java/ie/tcd/wayfinder/highlevel/navigation/SwaggerConfig.java
> +        return new ApiInfoBuilder().title("Trinity Wayfinders Authentication Module")
Please change it to HLAPI module

2019-02-22 13:57 UTC, ats0stv commented on Code/HighLevelAPI/src/main/java/ie/tcd/wayfinder/highlevel/navigation/SwaggerConfig.java
> +                                   .description("Authentication ReST API Documentation")
Give Description of HLAPI

2019-02-22 13:57 UTC, ats0stv commented on Code/HighLevelAPI/src/main/resources/application.properties
> +security.oauth2.resource.user-info-uri=http://localhost:8080/api/user/me
Please add a new line

2019-02-26 10:56 UTC, ats0stv approved these changes

2019-02-26 11:04 UTC, GrennanM approved these changes

2019-02-26 14:18 UTC, bonellon approved these changes

2019-02-26 23:15 UTC, merged