Zihan/wd 71 ionic signup
trinitywayfinders/WayFinder pull request #29
Opened 2019-02-28 14:07 UTC by zihan0

sign up page finished

2019-03-12 13:41 UTC, bonellon requested changes

2019-03-12 13:41 UTC, bonellon commented on UI/basicGUI/src/pages/signup/signup.ts
> +      'username': this.usrname,
usrname -> username

2019-03-12 13:41 UTC, bonellon commented on UI/basicGUI/src/pages/signup/signup.ts
> +  //alert for unmatch imput passwords
imput

2019-03-12 13:41 UTC, bonellon commented on UI/basicGUI/src/pages/signup/signup.ts
> +      'password': this.passwd
can we use 'password': this.passwd1 and avoid having 3 password variables?

2019-03-12 14:51 UTC, zihan0 commented on UI/basicGUI/src/pages/signup/signup.ts
> +      'username': this.usrname,
no can do

2019-03-12 14:51 UTC, zihan0 commented on UI/basicGUI/src/pages/signup/signup.ts
> +      'password': this.passwd
done

2019-03-12 14:51 UTC, zihan0 commented on UI/basicGUI/src/pages/signup/signup.ts
> +  //alert for unmatch imput passwords
fixed, thank you

2019-03-13 10:23 UTC, bonellon approved these changes

2019-03-14 11:48 UTC, Jamesxu182 approved these changes

2019-03-14 11:48 UTC, merged