Yifan/database schema diagram
trinitywayfinders/WayFinder pull request #9
Opened 2019-02-07 15:38 UTC by Jamesxu182

Add initial database schema diagram. please use MySQL Workbench. Feedbacks are welcome.

2019-02-07 15:52 UTC, ats0stv requested changes
1. Can you please move the Use case diagram to a dedicated branch
2. Please also include a rendered version of the schema diagram as PDF or JPG

2019-02-07 16:31 UTC, bonellon commented
TranspotionOption -> TransportationOption

2019-02-07 16:50 UTC, ats0stv commented
@Jamesxu182 As discussed please take care of the following
1. Scalability in terms of transportation options
2. Every table 'should' have a Primary Key
3. unique constraint on the user name
4. unique constraint for admin user name
5. Use of FROM field in notification table?
6. Provision for storing the city/region/area/zone information in terms of lat and long along with the meta like various env metrics
7. Provision for persisting sustainability metrics

2019-02-12 11:07 UTC, bonellon submitted a review, later dismissed

2019-02-18 12:30 UTC, ats0stv approved these changes

2019-02-18 12:49 UTC, bonellon approved these changes

2019-02-18 13:47 UTC, merged